### ISSUE TITLE
XP and YP purpose in python-gyro-accel-compass example?

### ISSUE THREAD

**Issue by tagaf** [mwilliams03/BerryIMU#3]
Hi, reading your code, it's not clear to me what is the purpose of these two parameters, are strictly related to kalmanFilterX and kalmanFilterY respectively? or they just dont depend on which angle you're considering? in this case why XPs parameters are never used? they have been only declared?

**Comment by mwilliams03** [comment]
You spotted an error.
XP should be used for X angle and YP should be used for Y angle.
I have corrected the code.
