### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Ssabaker** [mwilliams03/BerryIMU#7]
I am currently trying to work my way through the tutorials, however, I can't get the three tutorials to compile due to various errors.  The first and the third have errors where I2C_SMBUS_BLOCK_MAX is undeclared while the second one can't find the directory for "SDL.h". Is there anything that I might be missing here? Thank you

**Comment by mwilliams03** [comment]
Which program are you using where you get these errors?

**Comment by Ssabaker** [comment]
I'm trying to run it through the terminal by following the read me's. What program should i be using?

**Comment by mwilliams03** [comment]
If you are just after angles and compass heading, then use this code;
https://github.com/mwilliams03/BerryIMU/tree/master/python-BerryIMU-gryo-accel-compass

**Comment by Ssabaker** [comment]
Now I'm getting an error for line 36: bus = smbus.SMBus(1)
But it's importing smbus

**Comment by Ssabaker** [comment]
went back and reinstall the smbus and its working now

**Comment by Ssabaker** [comment]
appreciate the help, thank you
