### ISSUE TITLE
I2C_SMBUS_BLOCK_MAX

### ISSUE THREAD

**Issue by dmieszkowski** [mwilliams03/BerryIMU#8]
sensor.c:121:14: error: ‘I2C_SMBUS_BLOCK_MAX’ undeclared (first use in this function) while compiling gyro_accelerometer_tutorial01.c

**Comment by mwilliams03** [comment]
Have you done everything on this page; [http://ozzmaker.com/i2c/](http://ozzmaker.com/i2c/)

You are missing `sudo apt install libi2c-dev`
